# Generated by Django 4.1.8 on 2023-04-09 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_code_alter_company_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='344b5415916a4616bcb27ab5b891dee6', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 8, 36, 43, 498384, tzinfo=datetime.timezone.utc)),
        ),
    ]
