# Generated by Django 4.1.7 on 2023-04-13 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_code_alter_company_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='593adddf4c2b45dcb9d40dc36266e90f', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 12, 22, 30, 112800, tzinfo=datetime.timezone.utc)),
        ),
    ]
