# Generated by Django 4.1.8 on 2023-04-14 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_company_code_alter_company_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='7b2039d5b20345b59e770d76d7c533dc', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 17, 14, 49, 492276, tzinfo=datetime.timezone.utc)),
        ),
    ]
