# Generated by Django 4.1.8 on 2023-04-24 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_company_code_alter_company_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='500c23c972e140b3823623893f8ec698', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 12, 13, 40, 725726, tzinfo=datetime.timezone.utc)),
        ),
    ]
