# Generated by Django 4.1.8 on 2023-05-01 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_alter_company_code_alter_company_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='fd7df9f1b4224339985a9fb1f22b72d3', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 18, 46, 17, 136280, tzinfo=datetime.timezone.utc)),
        ),
    ]
