# Generated by Django 4.1.9 on 2023-05-22 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_alter_company_code_alter_company_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='01e170025d7241869200ac44c7ec97a7', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 17, 40, 37, 124520, tzinfo=datetime.timezone.utc)),
        ),
    ]
