# Generated by Django 4.1.9 on 2023-05-22 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_alter_company_code_alter_company_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='a7ae66621eab4b9bb50343e1191a0888', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 18, 41, 3, 462216, tzinfo=datetime.timezone.utc)),
        ),
    ]
