# Generated by Django 4.1.8 on 2023-04-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_alter_company_code_alter_company_code_expiration'),
        ('project', '0002_project_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_project', to='company.company'),
        ),
    ]
