# Generated by Django 4.1.7 on 2023-04-04 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Not Started', max_length=20)),
                ('admins', models.ManyToManyField(related_name='admin_projects', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participant_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
