# Generated by Django 4.1.8 on 2023-04-09 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_code_alter_company_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='eb8fce78a8e04c87986a8577acc2cd1e', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 8, 8, 33, 235002, tzinfo=datetime.timezone.utc)),
        ),
    ]
