# Generated by Django 4.1.8 on 2023-04-09 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_code_alter_company_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='106db3413f704257bd1ce2f383ec1c07', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 8, 50, 37, 867566, tzinfo=datetime.timezone.utc)),
        ),
    ]
