# Generated by Django 4.1.8 on 2023-04-11 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_code_alter_company_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='8d459cbf1362471e8926a3b36d79df0d', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 15, 19, 32, 120514, tzinfo=datetime.timezone.utc)),
        ),
    ]
