# Generated by Django 4.1.7 on 2023-04-11 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_company_code_alter_company_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='93aed7ccbd7c448aaa259013880e8966', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 19, 21, 58, 946857, tzinfo=datetime.timezone.utc)),
        ),
    ]
