# Generated by Django 4.1.8 on 2023-04-14 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_company_code_alter_company_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='aa88f2e696134b229b253ef8b91876f2', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 17, 14, 36, 472586, tzinfo=datetime.timezone.utc)),
        ),
    ]
