# Generated by Django 4.1.8 on 2023-04-24 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_company_code_alter_company_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='7f4cae28719b418ca34b5b5b70660ef2', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 12, 13, 21, 826074, tzinfo=datetime.timezone.utc)),
        ),
    ]
