# Generated by Django 4.1.8 on 2023-04-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
